# Generated by Django 2.1.5 on 2020-06-07 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='ФИО', max_length=100)),
                ('email_or_phone', models.CharField(help_text='Электронная почта или номер телефона', max_length=100)),
                ('comment', models.CharField(help_text='Комментарий', max_length=600)),
                ('datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Дата публикации', null=True)),
                ('picture_id', models.CharField(help_text='Картина', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='ФИО', max_length=100)),
                ('country', models.CharField(help_text='Страна', max_length=100)),
                ('city', models.CharField(help_text='Город', max_length=100)),
                ('telephone_number', models.CharField(help_text='Телефонный номер', max_length=25)),
                ('nickname', models.CharField(blank=True, help_text='Никнейм', max_length=200, null=True)),
                ('keep_in_touch', models.CharField(blank=True, choices=[('t', 'Telegram'), ('v', 'Viber'), ('m', 'Мобильный телефон')], default='t', help_text='Продолжать общение посредством', max_length=1)),
                ('receive', models.CharField(blank=True, choices=[('n', 'самовывоз из Новой Почты'), ('u', 'самовывоз из Укрпочты'), ('c', 'курьер Новой Почты'), ('m', 'при встрече (только в Одессе)')], default='n', help_text='Способ получения', max_length=1)),
                ('post_office', models.CharField(blank=True, help_text='Почтовое отделение', max_length=200, null=True)),
                ('address', models.CharField(blank=True, help_text='Адрес', max_length=200, null=True)),
                ('payment', models.CharField(blank=True, choices=[('o', 'оплатить заказ при получении'), ('p', 'перевод на карту')], default='o', help_text='Способ оплаты', max_length=1)),
                ('total_amount', models.IntegerField(help_text='Общая стоимость')),
                ('comment', models.CharField(blank=True, help_text='Комментарий', max_length=500, null=True)),
                ('picture_with_price_list', models.CharField(help_text='Комментарий', max_length=600)),
                ('datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Дата оформления')),
            ],
        ),
    ]
