# Generated by Django 2.1.5 on 2020-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='ФИО', max_length=100)),
                ('country', models.CharField(help_text='Страна', max_length=100)),
                ('city', models.CharField(help_text='Город', max_length=100)),
                ('telephone_number', models.CharField(help_text='Телефонный номер', max_length=25)),
                ('nickname', models.CharField(help_text='Никнейм', max_length=200, null=True)),
                ('keep_in_touch', models.CharField(blank=True, choices=[('t', 'Telegram'), ('v', 'Viber'), ('m', 'Мобильный телефон')], default='t', help_text='Продолжать общение посредством', max_length=1)),
                ('receive', models.CharField(blank=True, choices=[('n', 'самовывоз из Новой Почты'), ('u', 'самовывоз из Укрпочты'), ('c', 'курьер Новой Почты'), ('m', 'при встрече (только в Одессе)')], default='n', help_text='Способ получения', max_length=1)),
                ('post_office', models.CharField(help_text='Почтовое отделение', max_length=200)),
                ('address', models.CharField(help_text='Адрес', max_length=200)),
                ('payment', models.CharField(blank=True, choices=[('o', 'оплатить заказ при получении'), ('p', 'перевод на карту')], default='o', help_text='Способ оплаты', max_length=1)),
                ('total_amount', models.IntegerField(help_text='Общая стоимость')),
                ('comment', models.CharField(help_text='Комментарий', max_length=500)),
                ('picture_with_price_list', models.CharField(help_text='Комментарий', max_length=600)),
                ('datetime', models.DateTimeField(blank=True, default='0000-00-00', help_text='Дата оформления заказа')),
            ],
        ),
    ]
