# Generated by Django 2.1.5 on 2020-06-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
