# Generated by Django 2.1.5 on 2020-03-27 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200323_2341'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='ФИО', max_length=100)),
                ('email_or_phone', models.CharField(help_text='Электронная почта или номер телефона', max_length=100)),
                ('comment', models.CharField(help_text='Комментарий', max_length=600)),
                ('datetime', models.DateTimeField(blank=True, default='0000-00-00', help_text='Дата публикации комментария')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.Picture')),
            ],
        ),
    ]
