# Generated by Django 2.1.5 on 2020-06-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_comment_is_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
