# Generated by Django 2.2.2 on 2019-08-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testRow', models.CharField(help_text='hello!', max_length=20)),
            ],
        ),
    ]
