# Generated by Django 2.2.2 on 2019-09-03 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный номер картины в галерее', primary_key=True, serialize=False)),
                ('Name', models.CharField(help_text='Название картины', max_length=100)),
                ('CreationDate', models.DateField(blank=True, null=True)),
                ('SizeHeight', models.FloatField(blank=True, help_text='Вводите высоту изделия в сантиметрах')),
                ('SizeWeight', models.FloatField(blank=True, help_text='Вводите ширину изделия в сантиметрах')),
                ('Materials', models.CharField(help_text='Ткань, кисти, бумага...', max_length=500)),
                ('Description', models.CharField(help_text='Добавьте описание картины', max_length=1000)),
                ('status', models.CharField(blank=True, choices=[('a', 'Author ownership'), ('p', 'Private collection'), ('s', 'On sale')], default='o', help_text='Состояние картины', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='testModel',
        ),
    ]
