# Generated by Django 2.0 on 2019-09-04 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190903_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Название выставки относящейся к каталогу', max_length=100)),
                ('Preview', models.ImageField(upload_to='photos/pW/Ct')),
                ('CreationDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='Название работы', max_length=100)),
                ('Preview', models.ImageField(upload_to='photos/pW/Pd')),
                ('WorkPhoto', models.ImageField(upload_to='photos/pD/Wp')),
                ('PhotoReport', models.ImageField(upload_to='photos/pD/Pr')),
                ('ReleaseYear', models.DateField(blank=True, help_text='Дата сдачи диплома', null=True)),
                ('SizeHeight', models.FloatField(blank=True, help_text='Вводите высоту изделия в сантиметрах')),
                ('SizeWidth', models.FloatField(blank=True, help_text='Вводите ширину изделия в сантиметрах')),
                ('StudentsFIO', models.CharField(help_text='ФИО студента', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Название выставки', max_length=100)),
                ('CreationDate', models.DateField(blank=True, null=True)),
                ('Preview', models.ImageField(upload_to='photos/pW/En')),
                ('Place', models.CharField(help_text='Место провождения', max_length=200)),
                ('Adress', models.CharField(help_text='Адрес', max_length=200)),
                ('Managers', models.CharField(help_text='ФИО организаторов', max_length=400)),
                ('Curator', models.CharField(help_text='ФИО курвторов', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Methodical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Название методички', max_length=100)),
                ('Preview', models.ImageField(upload_to='photos/pW/Mh')),
                ('Author', models.CharField(help_text='ФИО автора', max_length=200)),
                ('CreationDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Наименование статьи', max_length=100)),
                ('Preview', models.ImageField(upload_to='photos/pW/Ps')),
                ('Author', models.CharField(help_text='ФИО автора', max_length=200)),
                ('CreationDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название техники', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='SizeWeight',
            new_name='SizeWidth',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='Name',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='picture',
            name='Photos',
            field=models.ImageField(default=0, upload_to='photos/pG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='Preview',
            field=models.ImageField(default=0, upload_to='photos/pW/Pg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='idTechnique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Technique'),
        ),
        migrations.AddField(
            model_name='picture',
            name='idTechnique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Technique'),
        ),
    ]
