# Generated by Django 2.1.5 on 2020-06-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200323_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['Title']},
        ),
    ]
