# Generated by Django 2.1.5 on 2020-03-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200309_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Picture',
        ),
    ]
