# Generated by Django 2.1.5 on 2019-11-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190904_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoDiploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/photos/diploma/main-photos')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/photos/gallery/main-photos')),
            ],
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='Press',
        ),
        migrations.RemoveField(
            model_name='diploma',
            name='PhotoReport',
        ),
        migrations.RemoveField(
            model_name='diploma',
            name='WorkPhoto',
        ),
        migrations.RemoveField(
            model_name='diploma',
            name='idTechnique',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='Photos',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='idTechnique',
        ),
        migrations.AddField(
            model_name='diploma',
            name='Description',
            field=models.CharField(default='put the text', help_text='Добавьте описание картины', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diploma',
            name='IdTechnique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tkd', to='catalog.Technique'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='Catalog',
            field=models.FileField(default='put the file', upload_to='media/files/catalogs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='methodical',
            name='Path',
            field=models.FileField(default='put the file', upload_to='media/files/methodical'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='IdTechnique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tkp', to='catalog.Technique'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='ReleaseYear',
            field=models.DateField(blank=True, default='put the data', help_text='Дата сдачи диплома'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='Preview',
            field=models.ImageField(upload_to='media/photos/diploma/preview'),
        ),
        migrations.AlterField(
            model_name='methodical',
            name='CreationDate',
            field=models.DateField(blank=True, default='put the data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='methodical',
            name='Preview',
            field=models.ImageField(upload_to='media/photos/methodical-pw'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='CreationDate',
            field=models.DateField(blank=True, default='put the file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='Preview',
            field=models.ImageField(upload_to='media/photos/gallery/preview'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Author ownership'), ('p', 'Private collection'), ('s', 'On sale')], default='s', help_text='Состояние картины', max_length=1),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='Path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg', to='catalog.Picture'),
        ),
        migrations.AddField(
            model_name='photodiploma',
            name='Path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd', to='catalog.Diploma'),
        ),
    ]
