# Generated by Django 2.1.5 on 2020-03-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200309_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='Hover',
            field=models.CharField(max_length=5),
        ),
    ]
