# Generated by Django 2.1.5 on 2020-03-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200309_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='Hover',
            field=models.BooleanField(default=False),
        ),
    ]
