# Generated by Django 2.1.5 on 2019-11-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191117_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='ReleaseYear',
            field=models.DateField(blank=True, default='0000-00-00', help_text='Дата сдачи диплома'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='CreationDate',
            field=models.DateField(blank=True, default='0000-00-00', null=True),
        ),
        migrations.AlterField(
            model_name='methodical',
            name='CreationDate',
            field=models.DateField(blank=True, default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='CreationDate',
            field=models.DateField(blank=True, default='0000-00-00'),
        ),
    ]
