# Generated by Django 2.1.5 on 2020-02-29 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191117_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Название', max_length=100)),
                ('Preview', models.ImageField(upload_to='C:/Users/LENOVO/Desktop/main/GitHub/diploma2019-2020/frontend/src/assets/pics/preview')),
                ('Author', models.CharField(help_text='ФИО автора', max_length=200)),
                ('CreationDate', models.DateField(blank=True, default='0000-00-00')),
                ('Path', models.FileField(upload_to='C:/Users/LENOVO/Desktop/main/GitHub/diploma2019-2020/frontend/src/assets/files')),
            ],
        ),
        migrations.RemoveField(
            model_name='photodiploma',
            name='Path',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='Path',
        ),
        migrations.AlterField(
            model_name='diploma',
            name='Preview',
            field=models.ImageField(upload_to='C:/Users/LENOVO/Desktop/main/GitHub/diploma2019-2020/frontend/src/assets/pics/preview'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='Catalog',
            field=models.FileField(upload_to='C:/Users/LENOVO/Desktop/main/GitHub/diploma2019-2020/frontend/src/assets/files'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='Preview',
            field=models.ImageField(upload_to='C:/Users/LENOVO/Desktop/main/GitHub/diploma2019-2020/frontend/src/assets/pics/preview'),
        ),
        migrations.AlterField(
            model_name='methodical',
            name='Path',
            field=models.FileField(upload_to='C:/Users/LENOVO/Desktop/main/GitHub/diploma2019-2020/frontend/src/assets/files'),
        ),
        migrations.AlterField(
            model_name='methodical',
            name='Preview',
            field=models.ImageField(upload_to='C:/Users/LENOVO/Desktop/main/GitHub/diploma2019-2020/frontend/src/assets/pics/preview'),
        ),
        migrations.AlterField(
            model_name='photodiploma',
            name='image',
            field=models.ImageField(upload_to='C:/Users/LENOVO/Desktop/main/GitHub/diploma2019-2020/frontend/src/assets/pics/main-photos'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(upload_to='C:/Users/LENOVO/Desktop/main/GitHub/diploma2019-2020/frontend/src/assets/pics/main-photos'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='IdTechnique',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tkp', to='catalog.Technique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='Preview',
            field=models.ImageField(upload_to='C:/Users/LENOVO/Desktop/main/GitHub/diploma2019-2020/frontend/src/assets/pics'),
        ),
    ]
